version: '3.9'
services:
  # lb: 
  #   build: ./.docker/lb/.
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./.docker/lb/cfg:/usr/local/etc/haproxy

  proxy:
    image: nginx:1.20.2-alpine
    #build: ./.docker/proxy/.
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./.docker/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - app
    networks:
      - proxy
    deploy: 
      replicas: 1 
      placement:
        constraints: [node.role == manager]

  app:
    #restart: always
    image: openjdk:18-jdk-alpine3.14
    #build: ./.docker/app/.
    ports:
    - 8080/tcp
    volumes:
    - ./.docker/app/build/wit-cicd-challenge.jar:/app/wit-cicd-challenge.jar
    entrypoint: java -jar /app/wit-cicd-challenge.jar
    deploy: 
      replicas: 1
      placement:
        constraints: [node.role == manager] 

networks:
  proxy: