version: "3.9"
services:
  loadbalance: 
    image: haproxy:lts-alpine3.14
    volumes:
    - ./.docker/lb/config:/usr/local/etc/haproxy
    - ./.docker/lb/certs:/etc/ssl/private
    networks:
    - backend
    ports: 
    - "80:80"  
    - "443:443"  

  proxy:
    image: nginx:1.20.2-alpine
    #build: ./.docker/proxy/.
    ports:
    - "80/tcp"
    volumes:
    - ./.docker/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - app
    networks:
      - backend
    deploy: 
      replicas: 1 
      placement:
        constraints: [node.role == manager]

  app:
    #restart: always
    image: openjdk:18-jdk-alpine3.14
    #build: ./.docker/app/.
    ports:
    - "8080/tcp"
    networks:
    - backend
    volumes:
    - ./.docker/app/build/wit-cicd-challenge.jar:/app/wit-cicd-challenge.jar
    entrypoint: java -jar /app/wit-cicd-challenge.jar
    deploy: 
      replicas: 1
      restart_policy:
        condition: on-failure  
      placement:
        constraints: [node.role == manager] 

networks:
  backend:
    driver: overlay