version: '3'
services:
  web:
   container_name: web
   build: ./.docker/web/.
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./.docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
   depends_on:
   - app

  app:
    container_name: app
    #restart: always
    build: ./.docker/app/.
    expose:
      - "8080"