version: '3.9'
services:
  # lb: 
  #   build: ./.docker/lb/.
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./.docker/lb/cfg:/usr/local/etc/haproxy

  proxy:
    image: nginx:1.20.2-alpine
    #build: ./.docker/proxy/.
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./.docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - app
    deploy: 
      replicas: 1 

  app:
    #restart: always
    image: 127.0.0.1:8080/wit-test
    build: ./.docker/app/.
    deploy: 
      replicas: 1 